log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

providers:
  docker:
    watch: true
    network: web
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
# Optional HTTPS setup
# entryPoints:
#   websecure:
#     address: ":443"
