FROM node:20-alpine
WORKDIR /app

# Copy only workspace configs first
COPY package.json package-lock.json* ./
COPY apps/frontend/package.json ./apps/frontend/
COPY packages/shared/drizzle/package.json ./packages/shared/drizzle/
COPY packages/shared/types/package.json ./packages/shared/types/

RUN npm install

# Copy the rest of the code
COPY . .

RUN apk add --no-cache curl
EXPOSE 3000
HEALTHCHECK --interval=5s --timeout=3s --retries=30 CMD curl -f http://localhost:3000/ || exit 1

CMD ["npm", "run", "dev", "--prefix", "apps/frontend"]
