FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache python3 make g++ vips-dev fftw-dev

COPY package.json package-lock.json* ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/frontend/package.json ./apps/frontend/
COPY packages/shared/drizzle/package.json ./packages/shared/drizzle/
COPY packages/shared/types/package.json ./packages/shared/types/
COPY packages/shared/mobile/package.json ./packages/shared/mobile/

ENV SHARP_FORCE_GLOBAL_LIBVIPS=1
RUN npm install

COPY . .

RUN npx nx run-many -t build --projects=@shared/drizzle,@shared/types --parallel=false --skip-nx-cache

WORKDIR /app/apps/backend
EXPOSE 4000

CMD ["npm", "run", "dev"]
