import "server-only";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../components/providers/theme-provider";
import JotaiProvider from "@/components/providers/jotai-provider";
import { Toaster } from "@/components/ui/toaster";
import SupabaseProvider from "@/components/providers/supabase-provider";
import SupabaseAuthProvider from "@/components/providers/supabase-auth-provider";
import { createClient } from "@/utils/supabase-server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <SupabaseAuthProvider serverSession={session}>
            <JotaiProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
              >
                {children}
                <Toaster />
              </ThemeProvider>
            </JotaiProvider>
          </SupabaseAuthProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
